// GENERATED by tools/terminus/bake_glyphs.py -- do not edit.
//
// Terminus (https://terminus-font.sourceforge.net/), SIL Open Font
// License 1.1 -- see tools/terminus/LICENSE. Bold strikes only.
//
// One uint32_t per pixel row, bit 0 = leftmost pixel. Drawn by
// gui/src/terminus_glyph*.cc as run-length rectangles at an INTEGER
// scale; see that header for why nothing here is ever resampled.
#pragma once

#include <cstdint>

namespace terminus {

struct Glyph {
    char32_t cp;
    int cellW;
    int cellH;
    const std::uint32_t* rows;   // cellH entries
};

// 'S': Terminus Bold 16px, 8x16
inline constexpr std::uint32_t kBold16_U0053[] = {
    0x00000000, 0x00000000, 0x0000003E, 0x00000063, 0x00000003, 0x00000003, 0x0000003E, 0x00000060,
    0x00000060, 0x00000063, 0x00000063, 0x0000003E, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

// 'F': Terminus Bold 16px, 8x16
inline constexpr std::uint32_t kBold16_U0046[] = {
    0x00000000, 0x00000000, 0x0000007F, 0x00000003, 0x00000003, 0x00000003, 0x0000001F, 0x00000003,
    0x00000003, 0x00000003, 0x00000003, 0x00000003, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

inline constexpr Glyph kBold16[] = {
    {U'\u0053', 8, 16, kBold16_U0053},
    {U'\u0046', 8, 16, kBold16_U0046},
};

// 'S': Terminus Bold 32px, 16x32
inline constexpr std::uint32_t kBold32_U0053[] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000FF8, 0x00001FFC,
    0x00003C1E, 0x0000380E, 0x0000380E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000001E, 0x00000FFC,
    0x00001FF8, 0x00003C00, 0x00003800, 0x00003800, 0x00003800, 0x0000380E, 0x0000380E, 0x00003C1E,
    0x00001FFC, 0x00000FF8, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

// 'F': Terminus Bold 32px, 16x32
inline constexpr std::uint32_t kBold32_U0046[] = {
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00003FFE, 0x00003FFE,
    0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x000007FE,
    0x000007FE, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E, 0x0000000E,
    0x0000000E, 0x0000000E, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

inline constexpr Glyph kBold32[] = {
    {U'\u0053', 16, 32, kBold32_U0053},
    {U'\u0046', 16, 32, kBold32_U0046},
};

}  // namespace terminus
