// GENERATED by tools/icon_font/build_icon_font.py -- do not edit.
//
// Icon glyphs live in assets/fonts/icons/matrix-icons.otf at Private
// Use Area codepoints and are baked into the shared MTSDF atlas by
// PlayerWindow::bakeIconGlyphs().
//
// Each icon is authored inside its own square DESIGN BOX, in ems,
// whose bottom edge sits on the baseline and whose left edge sits at
// x=0. The box (not the ink) maps onto the target rect, so icons keep
// their relative sizes -- and the box size sets the bake density, so
// it is chosen per icon to match where that icon is actually drawn.
// See the ICONS table in build_icon_font.py.
#pragma once

// play: 2 em box -> 192px cell, ink 0.833 x 1.222 em
static constexpr unsigned kIconCpPlay  = 0xE000;
static constexpr float    kIconBoxPlay = 2.0f;
// stop: 2 em box -> 192px cell, ink 0.889 x 0.889 em
static constexpr unsigned kIconCpStop  = 0xE001;
static constexpr float    kIconBoxStop = 2.0f;
// prev: 2 em box -> 192px cell, ink 1.167 x 1.111 em
static constexpr unsigned kIconCpPrev  = 0xE002;
static constexpr float    kIconBoxPrev = 2.0f;
// next: 2 em box -> 192px cell, ink 1.167 x 1.111 em
static constexpr unsigned kIconCpNext  = 0xE003;
static constexpr float    kIconBoxNext = 2.0f;
// settings: 1 em box -> 96px cell, ink 0.820 x 0.785 em
static constexpr unsigned kIconCpSettings  = 0xE004;
static constexpr float    kIconBoxSettings = 1.0f;
// warning: 1 em box -> 96px cell, ink 0.778 x 0.778 em
static constexpr unsigned kIconCpWarning  = 0xE005;
static constexpr float    kIconBoxWarning = 1.0f;
// quality: 0.5 em box -> 48.0px cell, ink 0.444 x 0.444 em
static constexpr unsigned kIconCpQuality  = 0xE006;
static constexpr float    kIconBoxQuality = 0.5f;

// Every icon codepoint, for bake + tests.
static constexpr unsigned kIconCodepoints[] = {
    kIconCpPlay,
    kIconCpStop,
    kIconCpPrev,
    kIconCpNext,
    kIconCpSettings,
    kIconCpWarning,
    kIconCpQuality,
};

// Smallest box any icon uses. ui_icons_test asserts every box is at
// least this, guarding against an icon being authored at a density
// so low it softens at the sizes the app draws it.
static constexpr float kIconBoxEmMin = 0.5f;

// Fingerprint of the baked icon geometry — see build_icon_font.py.
// Part of the atlas cache filename (ui_fonts.hh), so changing any
// icon invalidates the cache automatically instead of silently
// reusing glyphs baked at the old size.
static constexpr char kIconSetFingerprint[] = "72d43165";
