#!/usr/bin/env python3
"""Bake the Terminus glyphs bar A draws into gui/src/terminus_glyphs.gen.h.

Terminus is a BITMAP font, so it cannot go through the app's text engine
(RasterFont bakes from outlines, and FontStyle's four slots are all in use).
Instead the few glyphs the UI needs are baked here, one bit per pixel, and drawn
as run-length rectangles -- the method Economycs uses for its whole interface.

Ported from Economycs's tools/bake_terminus.py, with its defects fixed: the
inputs are read from THIS folder rather than /usr/share/fonts, paths are built
from this file's location rather than the working directory, a glyph that fails
to render is an error rather than a silently blank cell, and every pixel is
verified to be exactly 0 or 255.

Usage:  python3 tools/terminus/bake_glyphs.py      (needs Pillow)
The output is committed, so a normal C++ build never needs Python.
"""
import os
import sys

try:
    from PIL import Image, ImageFont
except ImportError as e:
    sys.exit(f"missing dependency: {e}\n  pip install pillow")

HERE = os.path.dirname(os.path.abspath(__file__))
HDR_OUT = os.path.join(HERE, "..", "..", "gui", "src", "terminus_glyphs.gen.h")
STRIKES = [16, 32]      # the only strikes that are integer multiples of 8x16
# The full printable-ASCII set MINUS lowercase (0x20 space through 0x7E '~',
# skipping 'a'-'z'): drawTerminusText folds ASCII lowercase to its capital's
# glyph at lookup time, so baking lowercase too would double the table for
# entries nothing ever looks up. Baking the WHOLE set up front, rather than
# one letter at a time the way `S`/`F` were, means a future Settings copy
# change never needs a re-bake -- only a genuinely new (non-ASCII) character
# would. Verified empirically during planning: all 69 chars bake cleanly at
# both strikes, no grey pixels, no missing glyphs (see the design spec).
GLYPHS = "".join(chr(c) for c in range(0x20, 0x7F) if not (0x61 <= c <= 0x7A))


def bake(size, ch):
    path = os.path.join(HERE, f"ter-u{size}b.otb")
    # BASIC layout: Raqm (the default) fails on some slots of a bitmap strike.
    font = ImageFont.truetype(path, size, layout_engine=ImageFont.Layout.BASIC)
    cw = int(round(font.getlength("M")))
    if cw <= 0 or cw > 32:
        sys.exit(f"{path}: cell width {cw} -- not a monospace strike <= 32 px?")
    mask = font.getmask(ch, mode="1")
    mw, mh = mask.size
    if not (mw and mh):
        sys.exit(f"{path}: no glyph for {ch!r}")
    glyph = Image.frombytes("L", (mw, mh), bytes(mask))
    img = Image.new("L", (cw, size), 0)
    img.paste(glyph, (0, font.getbbox(ch)[1]))   # getmask already includes x bearing
    rows = []
    for y in range(size):
        bits = 0
        for x in range(cw):
            v = img.getpixel((x, y))
            if v not in (0, 255):
                sys.exit(f"{path}: {ch!r} has a grey pixel ({v}) -- not a bitmap strike")
            if v:
                bits |= 1 << x            # bit 0 is the LEFTMOST pixel
        rows.append(bits)
    if not any(rows) and ch != " ":
        sys.exit(f"{path}: {ch!r} baked empty")
    return cw, size, rows


def main():
    out = [
        "// GENERATED by tools/terminus/bake_glyphs.py -- do not edit.",
        "//",
        "// Terminus (https://terminus-font.sourceforge.net/), SIL Open Font",
        "// License 1.1 -- see tools/terminus/LICENSE. Bold strikes only.",
        "//",
        "// One uint32_t per pixel row, bit 0 = leftmost pixel. Drawn by",
        "// gui/src/terminus_glyph*.cc as run-length rectangles at an INTEGER",
        "// scale; see that header for why nothing here is ever resampled.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace terminus {",
        "",
        "struct Glyph {",
        "    char32_t cp;",
        "    int cellW;",
        "    int cellH;",
        "    const std::uint32_t* rows;   // cellH entries",
        "};",
        "",
    ]
    for size in STRIKES:
        entries = []
        for ch in GLYPHS:
            cw, chh, rows = bake(size, ch)
            name = f"kBold{size}_U{ord(ch):04X}"
            out.append(f"// {ch!r}: Terminus Bold {size}px, {cw}x{chh}")
            out.append(f"inline constexpr std::uint32_t {name}[] = {{")
            for i in range(0, len(rows), 8):
                out.append("    " + ", ".join(f"0x{v:08X}" for v in rows[i:i + 8]) + ",")
            out.append("};")
            out.append("")
            entries.append(f"    {{U'\\u{ord(ch):04X}', {cw}, {chh}, {name}}},")
        out.append(f"inline constexpr Glyph kBold{size}[] = {{")
        out.extend(entries)
        out.append("};")
        out.append("")
    out.append("}  // namespace terminus")
    with open(HDR_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(HDR_OUT, HERE)}  ({len(GLYPHS)} glyph(s) x {len(STRIKES)} strikes)")


if __name__ == "__main__":
    main()
